'use server';
import { revalidatePath } from 'next/cache';
import { richiediContesto } from '@/server/identity/contesto';
import { aggiungiRigaComposizione, aggiornaRigaComposizione, rimuoviRigaComposizione } from '@/server/services/listino-composizioni-service';
import { aggiungiComposizioneABom } from '@/server/services/bom-composizione-service';
function numero(fd:FormData,n:string){const v=Number(fd.get(n));if(!Number.isFinite(v)||v<=0)throw new Error(`${n} non valido.`);return v;}
export async function aggiungiRigaComposizioneAzione(fd:FormData){const c=await richiediContesto({modulo:'catalogo',azione:'gestisci'});const composizioneId=String(fd.get('composizioneId')??'');const componenteId=String(fd.get('componenteId')??'');if(!composizioneId||!componenteId)throw new Error('Seleziona una composizione e un componente.');await aggiungiRigaComposizione(c.tenantId,composizioneId,componenteId,numero(fd,'quantita'));revalidatePath(`/admin/catalogo/listino/${composizioneId}`);}
export async function aggiornaRigaComposizioneAzione(fd:FormData){const c=await richiediContesto({modulo:'catalogo',azione:'gestisci'});const id=String(fd.get('id')??'');const composizioneId=String(fd.get('composizioneId')??'');if(!id||!composizioneId)throw new Error('Riga non valida.');await aggiornaRigaComposizione(c.tenantId,id,numero(fd,'quantita'));revalidatePath(`/admin/catalogo/listino/${composizioneId}`);}
export async function rimuoviRigaComposizioneAzione(fd:FormData){const c=await richiediContesto({modulo:'catalogo',azione:'gestisci'});const id=String(fd.get('id')??'');const composizioneId=String(fd.get('composizioneId')??'');if(!id||!composizioneId)throw new Error('Riga non valida.');await rimuoviRigaComposizione(c.tenantId,id);revalidatePath(`/admin/catalogo/listino/${composizioneId}`);}
export async function aggiungiComposizioneABomAzione(_p:{ok:boolean;message:string;bomId?:string},fd:FormData){try{const c=await richiediContesto({modulo:'richieste',azione:'gestisci'});const composizioneId=String(fd.get('composizioneId')??'');const bomId=String(fd.get('bomId')??'');if(!composizioneId||!bomId)throw new Error('Seleziona una BOM.');const r=await aggiungiComposizioneABom(c.tenantId,bomId,composizioneId);revalidatePath(`/admin/catalogo/listino/${composizioneId}`);revalidatePath(`/admin/bom/${bomId}`);return {ok:true,bomId,message:`${r.righeAggiunte} ${r.righeAggiunte===1?'riga aggiunta':'righe aggiunte'} alla BOM.`};}catch(e){return {ok:false,message:e instanceof Error?e.message:'Trasferimento non riuscito.'};}}
